const User = require("../models/User");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const sendEmail = require("../utils/sendEmail");
const addUserToSheet = require("../utils/googleSheet");
// ==========================
// Register User
// ==========================
const registerUser = async (req, res) => {
  try {
    // Get data from request body
    const { name, email, password } = req.body;

    // Check if user already exists
    const existingUser = await User.findOne({ email });

    if (existingUser) {
      return res.status(400).json({
        message: "User already exists",
      });
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Create new user
    const newUser = await User.create({
      name,
      email,
      password: hashedPassword,
    });
    await addUserToSheet(newUser);

    // ==========================
    // Send Welcome Email to User
    // ==========================
    await sendEmail(
  newUser.email,
  "🎉 Welcome to Open Library",
  `
  <div style="font-family: Arial, sans-serif; padding:20px;">
    <h1 style="color:#2563eb;">📚 Welcome to Open Library!</h1>

    <p>Hello <b>${newUser.name}</b>,</p>

    <p>Your account has been created successfully.</p>

    <p>You can now:</p>

    <ul>
      <li>📖 Browse books</li>
      <li>✍️ View authors</li>
      <li>📚 Explore our library</li>
      <li>🔐 Access your account securely</li>
    </ul>

    <br>

    <p>Regards,</p>
    <h3>Open Library Team</h3>
  </div>
  `
);

    // ==========================
    // Send Email to Admin
    // ==========================
    await sendEmail(
  process.env.ADMIN_EMAIL,
  "📢 New User Registered",
  `
  <div style="font-family: Arial, sans-serif; padding:20px;">
    <h2 style="color:#2563eb;">📚 Open Library</h2>
    <hr>

    <h3>New User Registration</h3>

    <table cellpadding="8">
      <tr>
        <td><b>Name</b></td>
        <td>${newUser.name}</td>
      </tr>

      <tr>
        <td><b>Email</b></td>
        <td>${newUser.email}</td>
      </tr>

      <tr>
        <td><b>User ID</b></td>
        <td>${newUser._id}</td>
      </tr>

      <tr>
        <td><b>Registration Time</b></td>
        <td>${new Date().toLocaleString()}</td>
      </tr>
    </table>

    <hr>

    <p>This email was automatically generated by the Open Library System.</p>
  </div>
  `
);

    // Send response
    res.status(201).json({
      message: "User Registered Successfully",
      user: newUser,
    });

  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
};

// ==========================
// Login User
// ==========================
const loginUser = async (req, res) => {
  try {

    const { email, password } = req.body;

    // Check if user exists
    const user = await User.findOne({ email });

    if (!user) {
      return res.status(404).json({
        message: "User not found",
      });
    }

    // Compare password
    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.status(401).json({
        message: "Invalid Password",
      });
    }

    // Generate JWT Token
    const token = jwt.sign(
      {
        id: user._id,
      },
      process.env.JWT_SECRET,
      {
        expiresIn: "1d",
      }
    );

    res.status(200).json({
      message: "Login Successful",
      token,
    });

  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
};

module.exports = {
  registerUser,
  loginUser,
};